### ISSUE TITLE
[BUG Report]: Variable Sample throws NullReferenceException

### ISSUE THREAD

**Issue by greuelpirat** [SciSharp/TensorFlow.NET#1005]
### Description

I tried the variable example on https://tensorflownet.readthedocs.io/en/latest/Variable.html

But it throws the following exception:

```
2023-03-11 16:10:46.326691: I tensorflow/core/platform/cpu_feature_guard.cc:193] This TensorFlow binary is optimized with oneAPI Deep Neural Network Library (oneDNN) to use the following CPU instructio
ns in performance-critical operations:  AVX2
To enable them in other operations, rebuild TensorFlow with the appropriate compiler flags.
Unhandled exception. System.NullReferenceException: Object reference not set to an instance of an object.
   at Tensorflow._FetchMapper.for_fetch(Object fetch, Graph graph)
   at Tensorflow._FetchHandler..ctor(Graph graph, Object fetches, Dictionary`2 feeds, Action feed_handles)
   at Tensorflow.BaseSession._run(Object fetches, FeedItem[] feed_dict)
   at Tensorflow.BaseSession.run(Operation op, FeedItem[] feed_dict)
   at Program.<Main>$(String[] args) in ....
```

### Reproduction Steps

```
var x = tf.Variable(10, name: "x");
using (var session = tf.Session())
{
    session.run(x.initializer);
    var result = session.run(x);
    Console.Write(result); // should be 10
}
```

### Configuration and Other Information

csproj:
```
<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <OutputType>Exe</OutputType>
        <TargetFramework>net6.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
    </PropertyGroup>

    <ItemGroup>
      <PackageReference Include="TensorFlow.NET" Version="0.100.4" />
      <PackageReference Include="SciSharp.TensorFlow.Redist" Version="2.11.0" />
      <PackageReference Include="SciSharp.TensorFlow.Redist-Windows-GPU" Version="2.10.0" />
    </ItemGroup>

</Project>
```

**Comment by Oceania2018** [comment]
Please reference the test [here](https://github.com/SciSharp/TensorFlow.NET/tree/master/test/TensorFlowNET.UnitTest/Basics). The doc you mentioned is out of date.
