### ISSUE TITLE
[BUG Report]: RuntimeError: Tensorflow.NET cannot find a backend. 

### ISSUE THREAD

**Issue by nikescar1** [SciSharp/TensorFlow.NET#1183]
### Description

I make a fresh project, install the packages, run the example code, and get the following error.

System.TypeInitializationException
  HResult=0x80131534
  Message=The type initializer for 'Tensorflow.Binding' threw an exception.
  Source=Tensorflow.Binding
  StackTrace:
   at Tensorflow.Binding.get_tf()
   at Tensorflow.NumPy.AutoNumPyAttribute.OnEntry(MethodExecutionArgs args)
   at Tensorflow.NumPy.np.array[T](T[] data)
   at TensorFlowTesting.Program.Main(String[] args) in C:\Users\nikes\Documents\source\repos\TensorFlowTesting\Program.cs:line 23

  This exception was originally thrown at this call stack:
    Tensorflow.tensorflow.tensorflow()
    Tensorflow.Binding.Binding()

Inner Exception 1:
RuntimeError: Tensorflow.NET cannot find a backend. Please install one of the following packages for your program: SciSharp.TensorFlow.Redist, SciSharp.TensorFlow.Redist-Linux-GPU, SciSharp.TensorFlow.Redist-Windows-GPU. For more details, please visit https://github.com/SciSharp/TensorFlow.NET. If it still not work after installing the backend, please submit an issue to https://github.com/SciSharp/TensorFlow.NET/issues

If any other info is needed I'd be glad to provide it.

### Reproduction Steps

I installed packages like so:
Install-Package TensorFlow.NET
Install-Package TensorFlow.Keras
Install-Package SciSharp.TensorFlow.Redist

When I run the example code I get the above error.

### Configuration and Other Information

- Windows 11 PC
- Visual Studio 17.7.2
- New Console App using .Net Framework 4.7.2

**Comment by AsakusaRinne** [comment]
Many apologizes for seeing this late. I'm too busy these days to watch all the issues. This is a known problem that `.NET Framework` does not have good support for backend package. There're generally two ways to solve it:

1. Upgrade your runtime version (net core is recommended).
2. Find the nuget package under the folder `C:\users\xxx\.nuget\packages` and then extract the `tensorflow.dll` from it. Finally put the dll in the output directory of your project (or add an reference).

**Comment by OwenSSH** [comment]
This can also be caused by missing visual c++ redist
https://aka.ms/vs/17/release/vc_redist.x64.exe

**Comment by jaroslav-hook** [comment]
none of the proposed  works  in my case

**Comment by le-tan-phuc** [comment]
Hi all, any solution so far? I faced the same problem, none of the proposed solution works.

**Comment by Folasayo-Samuel** [comment]
Facing same issude right now. @AsakusaRinne

**Comment by nihao-git** [comment]
Hello, the dll file cannot be referenced, VS pop-up error
![1716818981238](https://github.com/SciSharp/TensorFlow.NET/assets/53027001/6979d4c7-efe0-4d05-9aa7-be3ab3c6b47b)
@ @AsakusaRinne

**Comment by Folasayo-Samuel** [comment]
To resolve the issue with macOS:

### CPU version for MacOS
PM> Install-Package SciSharp.TensorFlow.Redist-OSX

### CPU version for Windows and Linux
PM> Install-Package SciSharp.TensorFlow.Redist

### GPU version for Windows (CUDA and cuDNN are required)
PM> Install-Package SciSharp.TensorFlow.Redist-Windows-GPU

### GPU version for Linux (CUDA and cuDNN are required)
PM> Install-Package SciSharp.TensorFlow.Redist-Linux-GPU

**Comment by zxyjoo** [comment]
.NET8, windows surface, ARM64 based PC (Snapdragon(R)) has the same issue, cannot find the backend

**Comment by ly576888069** [comment]
> .NET8, windows surface, ARM64 based PC (Snapdragon(R)) has the same issue, cannot find the backend

I set vs project target version x64,then i was no problem alert.
