### ISSUE TITLE
Cannot parse tensor from proto: dtype

### ISSUE THREAD

**Issue by Esther2013** [SciSharp/TensorFlow.NET#174]
ZerosConst
```csharp
Test Name:	ZerosConst
Test FullName:	TensorFlowNET.UnitTest.ConstantTest.ZerosConst
Test Source:	D:\Projects\TensorFlow.NET\test\TensorFlowNET.UnitTest\ConstantTest.cs : line 37
Test Outcome:	Failed
Test Duration:	0:00:00.1996647

Result StackTrace:	
at Tensorflow.Python.with[T](IPython py, Action`1 action) in D:\Projects\TensorFlow.NET\src\TensorFlowNET.Core\Python.cs:line 56
   at TensorFlowNET.UnitTest.ConstantTest.ZerosConst() in D:\Projects\TensorFlow.NET\test\TensorFlowNET.UnitTest\ConstantTest.cs:line 41
Result Message:	
Test method TensorFlowNET.UnitTest.ConstantTest.ZerosConst threw exception: 
System.Exception: Cannot parse tensor from proto: dtype: DT_INT32
tensor_shape {
  dim {
    size: 3
    name: "dim_0"
  }
  dim {
    size: 2
    name: "dim_1"
  }
}
tensor_content: "\000\000\000\000"

	 [[{{node small}}]]
Result StandardOutput:	
create_op: Const 'small', inputs: empty, control_inputs: empty, outputs: small:0
Cannot parse tensor from proto: dtype: DT_INT32
tensor_shape {
  dim {
    size: 3
    name: "dim_0"
  }
  dim {
    size: 2
    name: "dim_1"
  }
}
tensor_content: "\000\000\000\000"

	 [[{{node small}}]]
System.Exception: Cannot parse tensor from proto: dtype: DT_INT32
tensor_shape {
  dim {
    size: 3
    name: "dim_0"
  }
  dim {
    size: 2
    name: "dim_1"
  }
}
tensor_content: "\000\000\000\000"

	 [[{{node small}}]]
   at Tensorflow.Status.Check(Boolean throwException) in D:\Projects\TensorFlow.NET\src\TensorFlowNET.Core\Status\Status.cs:line 48
   at Tensorflow.BaseSession._call_tf_sessionrun(KeyValuePair`2[] feed_dict, TF_Output[] fetch_list, List`1 target_list) in D:\Projects\TensorFlow.NET\src\TensorFlowNET.Core\Sessions\BaseSession.cs:line 157
   at Tensorflow.BaseSession._do_run(List`1 target_list, List`1 fetch_list, Dictionary`2 feed_dict) in D:\Projects\TensorFlow.NET\src\TensorFlowNET.Core\Sessions\BaseSession.cs:line 132
   at Tensorflow.BaseSession._run(Object fetches, FeedItem[] feed_dict) in D:\Projects\TensorFlow.NET\src\TensorFlowNET.Core\Sessions\BaseSession.cs:line 87
   at Tensorflow.BaseSession.run(Object fetches, FeedItem[] feed_dict) in D:\Projects\TensorFlow.NET\src\TensorFlowNET.Core\Sessions\BaseSession.cs:line 41
   at TensorFlowNET.UnitTest.ConstantTest.<>c__DisplayClass3_0.<ZerosConst>b__0(Session sess) in D:\Projects\TensorFlow.NET\test\TensorFlowNET.UnitTest\ConstantTest.cs:line 43
   at Tensorflow.Python.with[T](IPython py, Action`1 action) in D:\Projects\TensorFlow.NET\src\TensorFlowNET.Core\Python.cs:line 51


```

**Comment by Oceania2018** [comment]
fixed
