### ISSUE TITLE
Tutorial throws NotImplementedException

### ISSUE THREAD

**Issue by S4ftl4den** [SciSharp/TensorFlow.NET#186]
TensorFlow.NET/test/TensorFlowNET.Examples/BasicOperations.cs is what I try to run. When it tries to do this line ("
Console.WriteLine($"Addition with variables: {sess.run(add, feed_dict)}");
") the exception comes up. I am using version 0.41 which I got from NuGet.

Also I had to copy the tensorflow.dll manuall to the built solution otherwise it wouldnt find it. There is no way around that, as it is provided with no header, so I can also not add it as a reference directly.

System.NotImplementedException
  HResult=0x80004001
  Message=_run subfeed
  Source=TensorFlow.NET
  StackTrace:
   at Tensorflow.BaseSession._run(Object fetches, FeedItem[] feed_dict)
   at Neuro_2.Form1.Tut2() in D:\Eigene Dat\Dokumente\1111111111\Visual_Studio_Programme\Neuro_2\Neuro_2\Form1.cs:line 77
   at Neuro_2.Form1.button2_Click(Object sender, EventArgs e) in D:\Eigene Dat\Dokumente\1111111111\Visual_Studio_Programme\Neuro_2\Neuro_2\Form1.cs:line 40
   at System.Windows.Forms.Control.OnClick(EventArgs e)
   at System.Windows.Forms.Button.OnClick(EventArgs e)
   at System.Windows.Forms.Button.OnMouseUp(MouseEventArgs mevent)
   at System.Windows.Forms.Control.WmMouseUp(Message& m, MouseButtons button, Int32 clicks)
   at System.Windows.Forms.Control.WndProc(Message& m)
   at System.Windows.Forms.ButtonBase.WndProc(Message& m)
   at System.Windows.Forms.Button.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.DebuggableCallback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)
   at System.Windows.Forms.UnsafeNativeMethods.DispatchMessageW(MSG& msg)
   at System.Windows.Forms.Application.ComponentManager.System.Windows.Forms.UnsafeNativeMethods.IMsoComponentManager.FPushMessageLoop(IntPtr dwComponentID, Int32 reason, Int32 pvLoopData)
   at System.Windows.Forms.Application.ThreadContext.RunMessageLoopInner(Int32 reason, ApplicationContext context)
   at System.Windows.Forms.Application.ThreadContext.RunMessageLoop(Int32 reason, ApplicationContext context)
   at Neuro_2.Program.Main() in D:\Eigene Dat\Dokumente\1111111111\Visual_Studio_Programme\Neuro_2\Neuro_2\Program.cs:line 16

**Comment by Oceania2018** [comment]
Released v0.4.2. Let me know if it works or not. @S4ftl4den

**Comment by S4ftl4den** [comment]
Works now. Thank you very much.
