### ISSUE TITLE
Shape error for gradients/Sum_grad/Tile 

### ISSUE THREAD

**Issue by Oceania2018** [SciSharp/TensorFlow.NET#193]
It throws error when run `LogisticRegression` example.

```shell
Shape must be rank 1 but is rank 2 for 'gradients/Sum_grad/Tile' (op: 'Tile') with input shapes: [1], [2].
System.Exception: Shape must be rank 1 but is rank 2 for 'gradients/Sum_grad/Tile' (op: 'Tile') with input shapes: [1], [2].
   at Tensorflow.Status.Check(Boolean throwException) in D:\Projects\TensorFlow.NET\src\TensorFlowNET.Core\Status\Status.cs:line 48
   at Tensorflow.ops._create_c_op[T](Graph graph, NodeDef node_def, T[] inputs, Operation[] control_inputs) in D:\Projects\TensorFlow.NET\src\TensorFlowNET.Core\ops.py.cs:line 167
```

**Comment by Oceania2018** [comment]
```shell
Dimension size must be evenly divisible by 10 but is 1 for 'gradients/add_grad/Reshape' (op: 'Reshape') with input shapes: [], [2] and with input tensors computed as partial shapes: input[1] = [?,10].
System.Exception: Dimension size must be evenly divisible by 10 but is 1 for 'gradients/add_grad/Reshape' (op: 'Reshape') with input shapes: [], [2] and with input tensors computed as partial shapes: input[1] = [?,10].
```

**Comment by Esther2013** [comment]
`mul_grad` is not correct, mssing `shape`.

![image](https://user-images.githubusercontent.com/33488376/54733221-887ab000-4b66-11e9-893f-3c8bcb530ed0.png)
