### ISSUE TITLE
Cannot train a simple CNN

### ISSUE THREAD

**Issue by thomaslundgaard** [SciSharp/TensorFlow.NET#279]
I am trying to train a very simple convolutional neural network with just a single layer, but I keep getting the following exception:

```
$> bin/x64/Debug/ConsoleApp1.exe
2019-07-02 15:43:11.201294: I tensorflow/core/platform/cpu_feature_guard.cc:141] Your CPU supports instructions that this TensorFlow binary was not compiled to use: AVX2
Operation 'conv2d/Conv2D' has no attr named 'explicit_paddings'.
System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation. ---> System.Exception: Operation 'conv2d/Conv2D' has no attr named 'explicit_paddings'.
   at Tensorflow.Status.Check(Boolean throwException)
   at Tensorflow.Operation.get_attr(String name)
   at Tensorflow.Gradients.nn_grad._Conv2DGrad(Operation op, Tensor[] grads)
   --- End of inner exception stack trace ---
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Object[] arguments, Signature sig, Boolean constructor)
   at System.Reflection.RuntimeMethodInfo.UnsafeInvokeInternal(Object obj, Object[] parameters, Object[] arguments)
   at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at System.RuntimeType.InvokeMember(String name, BindingFlags bindingFlags, Binder binder, Object target, Object[] providedArgs, ParameterModifier[] modifiers, CultureInfo culture, String[] namedParams)
   at Tensorflow.ops.<>c__DisplayClass2_1.<get_gradient_function>b__2(Operation oper, Tensor[] out_grads)
   at Tensorflow.gradients_util.<>c__DisplayClass0_3.<_GradientsHelper>b__5(NameScope scope1)
   at Tensorflow.Python.with[T](T py, Action`1 action)
System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation. ---> System.Exception: Operation 'conv2d/Conv2D' has no attr named 'explicit_paddings'.
   at Tensorflow.Status.Check(Boolean throwException)
   at Tensorflow.Operation.get_attr(String name)
   at Tensorflow.Gradients.nn_grad._Conv2DGrad(Operation op, Tensor[] grads)
   --- End of inner exception stack trace ---
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Object[] arguments, Signature sig, Boolean constructor)
   at System.Reflection.RuntimeMethodInfo.UnsafeInvokeInternal(Object obj, Object[] parameters, Object[] arguments)
   at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at System.RuntimeType.InvokeMember(String name, BindingFlags bindingFlags, Binder binder, Object target, Object[] providedArgs, ParameterModifier[] modifiers, CultureInfo culture, String[] namedParams)
   at Tensorflow.ops.<>c__DisplayClass2_1.<get_gradient_function>b__2(Operation oper, Tensor[] out_grads)
   at Tensorflow.gradients_util.<>c__DisplayClass0_3.<_GradientsHelper>b__5(NameScope scope1)
   at Tensorflow.Python.with[T](T py, Action`1 action)
   at Tensorflow.gradients_util.<>c__DisplayClass0_0.<_GradientsHelper>b__0(NameScope scope)
   at Tensorflow.Python.with[T](T py, Action`1 action)

Unhandled Exception: System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation. ---> System.Exception: Operation 'conv2d/Conv2D' has no attr named 'explicit_paddings'.
   at Tensorflow.Status.Check(Boolean throwException)
   at Tensorflow.Operation.get_attr(String name)
   at Tensorflow.Gradients.nn_grad._Conv2DGrad(Operation op, Tensor[] grads)
   --- End of inner exception stack trace ---
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Object[] arguments, Signature sig, Boolean constructor)
   at System.Reflection.RuntimeMethodInfo.UnsafeInvokeInternal(Object obj, Object[] parameters, Object[] arguments)
   at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at System.RuntimeType.InvokeMember(String name, BindingFlags bindingFlags, Binder binder, Object target, Object[] providedArgs, ParameterModifier[] modifiers, CultureInfo culture, String[] namedParams)
   at Tensorflow.ops.<>c__DisplayClass2_1.<get_gradient_function>b__2(Operation oper, Tensor[] out_grads)
   at Tensorflow.gradients_util.<>c__DisplayClass0_3.<_GradientsHelper>b__5(NameScope scope1)
   at Tensorflow.Python.with[T](T py, Action`1 action)
   at Tensorflow.gradients_util.<>c__DisplayClass0_0.<_GradientsHelper>b__0(NameScope scope)
   at Tensorflow.Python.with[T](T py, Action`1 action)
   at Tensorflow.gradients_util._GradientsHelper(Tensor[] ys, Tensor[] xs, Tensor[] grad_ys, String name, Boolean colocate_gradients_with_ops, Boolean gate_gradients, Int32 aggregation_method, Tensor[] stop_gradients, Graph src_graph)
   at Tensorflow.Optimizer.compute_gradients(Tensor loss, List`1 var_list, Nullable`1 aggregation_method, GateGradientType gate_gradients, Boolean colocate_gradients_with_ops, Tensor grad_loss)
   at Tensorflow.Optimizer.minimize(Tensor loss, RefVariable global_step, List`1 var_list, GateGradientType gate_gradients, Nullable`1 aggregation_method, Boolean colocate_gradients_with_ops, String name, Tensor grad_loss)
   at ConsoleApp1.Program.Main(String[] args) in C:\Temp\Scratchpad\tfdotnet\ConsoleApp1\Program.cs:line 22
```

Here is the program I am running:

```
using System;
using Tensorflow;
using NumSharp;

namespace ConsoleApp1
{
    class Program
    {
        static void Main(string[] args)
        {
            var input = tf.placeholder(tf.float32, new TensorShape(1, 16, 32, 1));

            var net = tf.layers.conv2d(input, 16, new int[] { 3, 3 });
            net = tf.sum(net, 1, keep_dims: true);
            net = tf.sum(net, 2, keep_dims: true);
            net = tf.sum(net, 3, keep_dims: true);

            var target = tf.placeholder(tf.float32, new TensorShape(1, 1, 1, 1));
            var loss = tf.reduce_sum(tf.square(net - target));

            var adam = new Tensorflow.Train.AdamOptimizer(0.01f);
            var operation = adam.minimize(loss);

            var sess = tf.Session();

            for (int epoch = 0; epoch < 100; epoch++)
            {
                var x = np.ones(new Shape(12, 16, 32, 1), dtype:typeof(float));
                var y = np.ones(new Shape(12, 1, 1, 1), dtype:typeof(float));
                sess.run(operation, new FeedItem(input, x), new FeedItem(target, y));
                Console.WriteLine($"Epoch {epoch}: cost = {sess.run(loss, new FeedItem(input, x), new FeedItem(target, y))}");
            }

            return;
        }
    }
}
```

The only installed nugets in the project are NumSharp 0.10.3 and TensorFlow.NET 0.8.3 (and their dependencies).
This is a .NET framework 4.6.1 console application.

Any idea of what is going on?

Thanks in advance.

PS: You are making some cool projects here that could be very useful in my work. Keep up the good work!

**Comment by Oceania2018** [comment]
Please replace the `tensorflow.dll` with https://github.com/SciSharp/TensorFlow.NET/tree/master/tensorflowlib/runtimes/win-x64/native.

This issue will be fixed permanent once `Microsoft ML.NET Team` migrates their NuGet [Microsoft.ML.TensorFlow.Redist](https://www.nuget.org/packages/Microsoft.ML.TensorFlow.Redist) package to `TenaorFlow.NET` repo.

**Comment by acifonelli** [comment]
I had the same problem, but the error was still there after the common approach @Oceania2018 is suggesting.

1. Make sure you have CUDA v10 and cuDNN 7.3.1 installed on your machine;
2. Add the path to your CUDA installation (default is: `C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v10.0`) and your cuDNN library (`c:\tools\cudnn-10.0-v7.3.1\cuda` in my case) to your `Path` environment variable.

If it does not solve the problem, you can also try to:
1. Clone the TensorFlow.NET repository;
2. Replace the dll as suggested;
3. Pack a NuGet package with a different version number from the solution;
4. Add the output directory among the NuGet package sources;
5. let your project reference the version you specified.

**Comment by Oceania2018** [comment]
@acifonelli @thomaslundgaard I'm sure it will work once you replace the tensorflow.dll instead the one in zip. Tensorflow v1.14 added the `explicit_paddings` attribute which not compatile with < `v1.14`.

**Comment by thomaslundgaard** [comment]
Yes, replacing the dll fixed my issue. Thanks!

**Comment by PratapMehra** [comment]
I have the same issue. @Oceania2018 could you update the path of dll as the current one is not working.

**Comment by Oceania2018** [comment]
@PratapMehra Try this [TensorFlow Redistribution](https://www.nuget.org/packages/SciSharp.TensorFlow.Redist/1.14.1) version.
