### ISSUE TITLE
Incompatible shapes for YOLOv3

### ISSUE THREAD

**Issue by Oceania2018** [SciSharp/TensorFlow.NET#424]
Exception threw when run YOLOv3:

```shell
Incompatible shapes: [6,11,11,3,1] vs. [6,11,11,3,1,1]
         [[{{node define_loss/bigger_box_loss/mul_13}}]]
Tensorflow.TensorflowException: Incompatible shapes: [6,11,11,3,1] vs. [6,11,11,3,1,1]
         [[{{node define_loss/bigger_box_loss/mul_13}}]]
   at Tensorflow.BaseSession._call_tf_sessionrun(KeyValuePair`2[] feed_dict, TF_Output[] fetch_list, List`1 target_list) in 
D:\SciSharp\TensorFlow.NET\src\TensorFlowNET.Core\Sessions\BaseSession.cs:line 246
```

**Comment by Nucs** [comment]
I believe [tf.broadcast_to](https://www.tensorflow.org/api_docs/python/tf/broadcast_to) can help you with that.

**Comment by Oceania2018** [comment]
Upgrade to v0.12, another exception threw:
```csharp
2019-11-04 06:14:26.003412: I tensorflow/core/platform/cpu_feature_guard.cc:142] Your CPU supports instructions that this TensorFlow binary was not compiled to use: AVX2
TensorFlow Binary v1.14.1
TensorFlow.NET v0.12.0.0
[0]: YOLOv3
11/4/2019 12:14:26 PM Starting YOLOv3
System.NotImplementedException: IsWhileContext
   at Tensorflow.Operations.ControlFlowContext.IsWhileContext()
   at Tensorflow.control_flow_util.GetContainingWhileContext(ControlFlowContext ctxt, ControlFlowContext stop_ctxt)
   at Tensorflow.control_flow_util.CheckInputFromValidContext(Operation op, Operation input_op)
   at Tensorflow.Operation._control_flow_post_processing()
```

**Comment by Oceania2018** [comment]
```csharp
System.InvalidCastException: Unable to cast object of type 'System.Single' to type 'Tensorflow.ITensorOrTensorArray'.
   at Tensorflow.control_flow_ops.<>c__19`1.<cond>b__19_3(T x) in D:\SciSharp\TensorFlow.NET\src\TensorFlowNET.Core\Operations\control_flow_ops.cs:line 504
   at System.Linq.Enumerable.SelectArrayIterator`2.ToArray()
   at System.Linq.Enumerable.ToArray[TSource](IEnumerable`1 source)
   at Tensorflow.control_flow_ops.<>c__DisplayClass19_0`1.<cond>b__0(NameScope <p0>) in D:\SciSharp\TensorFlow.NET\src\TensorFlowNET.Core\Operations\control_flow_ops.cs:line 504
   at Tensorflow.Binding.tf_with[TIn,TOut](TIn py, Func`2 action) in D:\SciSharp\TensorFlow.NET\src\TensorFlowNET.Core\Binding.Util.cs:line 156
```

**Comment by Oceania2018** [comment]
```csharp
2019-11-05 23:01:34.084088: W tensorflow/core/framework/op_kernel.cc:1502] OP_REQUIRES failed at strided_slice_op.cc:107 : Invalid argument: Multiple ellipses in slice spec not allowed
2019-11-05 23:01:34.124432: W tensorflow/core/framework/op_kernel.cc:1502] OP_REQUIRES failed at strided_slice_op.cc:107 : Invalid argument: Multiple ellipses in slice spec not allowed
2019-11-05 23:01:34.167601: W tensorflow/core/framework/op_kernel.cc:1502] OP_REQUIRES failed at strided_slice_op.cc:107 : Invalid argument: Multiple ellipses in slice spec not allowed
2019-11-05 23:01:34.169512: W tensorflow/core/framework/op_kernel.cc:1502] OP_REQUIRES failed at strided_slice_op.cc:107 : Invalid argument: Multiple ellipses in slice spec not allowed
2019-11-05 23:01:34.174436: W tensorflow/core/framework/op_kernel.cc:1502] OP_REQUIRES failed at strided_slice_op.cc:107 : Invalid argument: Multiple ellipses in slice spec not allowed
2019-11-05 23:01:34.176334: W tensorflow/core/framework/op_kernel.cc:1502] OP_REQUIRES failed at strided_slice_op.cc:107 : Invalid argument: Multiple ellipses in slice spec not allowed
Multiple ellipses in slice spec not allowed
         [[{{node define_loss/smaller_box_loss/strided_slice_45}}]]
```

**Comment by Oceania2018** [comment]
The node `define_loss/bigger_box_loss/strided_slice_25` output shape should be `shape(?, ?, ? 3)`
