### ISSUE TITLE
Provided a prefix or suffix of None: tf.Tensor 'bidirectional_rnn/fw/fw/strided_slice:0' shape=() dtype=TF_INT32 and 0

### ISSUE THREAD

**Issue by Deep-Blue-2013** [SciSharp/TensorFlow.NET#450]
RNN Cell throw exception.
```csharp
Tensorflow.ValueError: Provided a prefix or suffix of None: tf.Tensor 'bidirectional_rnn/fw/fw/strided_slice:0' shape=() dtype=TF_INT32 and 0
   at Tensorflow.Operations.rnn_cell_impl._concat(Tensor prefix, Int32 suffix, Boolean static) in D:\SciSharp\TensorFlow.NET\src\TensorFlowNET.Core\Operations\NnOps\rnn_cell_impl.cs:line 53
   at Tensorflow.RnnCell.<>c__DisplayClass10_0.<_zero_state_tensors>b__0(Int32 s) in D:\SciSharp\TensorFlow.NET\src\TensorFlowNET.Core\Operations\NnOps\RNNCell.cs:line 97
   at System.Linq.Enumerable.SelectListIterator`2.ToList()
   at System.Linq.Enumerable.ToList[TSource](IEnumerable`1 source)
   at Tensorflow.Util.nest.map_structure[T](Func`2 func, T structure) in D:\SciSharp\TensorFlow.NET\src\TensorFlowNET.Core\Util\nest.py.cs:line 524
   at Tensorflow.RnnCell._zero_state_tensors(Int32 state_size, Tensor batch_size, TF_DataType dtype) in D:\SciSharp\TensorFlow.NET\src\TensorFlowNET.Core\Operations\NnOps\RNNCell.cs:line 95
   at Tensorflow.RnnCell.<>c__DisplayClass9_0.<zero_state>b__0(NameScope <p0>) in D:\SciSharp\TensorFlow.NET\src\TensorFlowNET.Core\Operations\NnOps\RNNCell.cs:line 87
   at Tensorflow.Binding.tf_with[T](T py, Action`1 action) in D:\SciSharp\TensorFlow.NET\src\TensorFlowNET.Core\Binding.Util.cs:line 141
   at Tensorflow.RnnCell.zero_state(Tensor batch_size, TF_DataType dtype) in D:\SciSharp\TensorFlow.NET\src\TensorFlowNET.Core\Operations\NnOps\RNNCell.cs:line 85
```

**Comment by Oceania2018** [comment]
Seems like `LSTMStateTuple(c=128, h=128)` is missing in `BasicLSTMCell`.
