### ISSUE TITLE
Run UnitTest Failed on GraphDef comparing

### ISSUE THREAD

**Issue by xuwaters** [SciSharp/TensorFlow.NET#470]
```
X Graph [61ms]
  Error Message:
   Assert.AreEqual failed. Expected:<{ "node": [ { "name": "feed", "op": "Placeholder", "attr": { "dtype": { "type": "DT_INT32" }, "shape": { "shape": { "unknownRank": true } } } }, { "name": "scalar", "op": "Const", "attr": { "value": { "tensor": { "dtype": "DT_INT32", "tensorShape": { }, "intVal": [ 3 ] } }, "dtype": { "type": "DT_INT32" } } }, { "name": "add", "op": "AddN", "input": [ "feed", "scalar" ], "attr": { "N": { "i": "2" }, "T": { "type": "DT_INT32" } } }, { "name": "neg", "op": "Neg", "input": [ "add" ], "attr": { "T": { "type": "DT_INT32" } } } ], "library": { }, "versions": { "producer": 134 } }>. Actual:<{ "node": [ { "name": "feed", "op": "Placeholder", "attr": { "shape": { "shape": { "unknownRank": true } }, "dtype": { "type": "DT_INT32" } } }, { "name": "scalar", "op": "Const", "attr": { "value": { "tensor": { "dtype": "DT_INT32", "tensorShape": { }, "intVal": [ 3 ] } }, "dtype": { "type": "DT_INT32" } } }, { "name": "add", "op": "AddN", "input": [ "feed", "scalar" ], "attr": { "T": { "type": "DT_INT32" }, "N": { "i": "2" } } }, { "name": "neg", "op": "Neg", "input": [ "add" ], "attr": { "T": { "type": "DT_INT32" } } } ], "library": { }, "versions": { "producer": 134 } }>.
  Stack Trace:
     at TensorFlowNET.UnitTest.CApiTest.EXPECT_EQ(Object expected, Object actual) in /data/will/workspace/learn/tf/TensorFlow.NET/test/TensorFlowNET.UnitTest/CApiTest.cs:line 18
   at TensorFlowNET.UnitTest.GraphTest.Graph() in /data/will/workspace/learn/tf/TensorFlow.NET/test/TensorFlowNET.UnitTest/GraphTest.cs:line 142

```

The two GraphDef are actually the same, but JSON strings are not equal.

```json
{ "node": [ { "name": "feed", "op": "Placeholder", "attr": { "dtype": { "type": "DT_INT32" }, "shape": { "shape": { "unknownRank": true } } } }, { "name": "scalar", "op": "Const", "attr": { "value": { "tensor": { "dtype": "DT_INT32", "tensorShape": { }, "intVal": [ 3 ] } }, "dtype": { "type": "DT_INT32" } } }, { "name": "add", "op": "AddN", "input": [ "feed", "scalar" ], "attr": { "N": { "i": "2" }, "T": { "type": "DT_INT32" } } }, { "name": "neg", "op": "Neg", "input": [ "add" ], "attr": { "T": { "type": "DT_INT32" } } } ], "library": { }, "versions": { "producer": 134 } }

{ "node": [ { "name": "feed", "op": "Placeholder", "attr": { "shape": { "shape": { "unknownRank": true } }, "dtype": { "type": "DT_INT32" } } }, { "name": "scalar", "op": "Const", "attr": { "value": { "tensor": { "dtype": "DT_INT32", "tensorShape": { }, "intVal": [ 3 ] } }, "dtype": { "type": "DT_INT32" } } }, { "name": "add", "op": "AddN", "input": [ "feed", "scalar" ], "attr": { "T": { "type": "DT_INT32" }, "N": { "i": "2" } } }, { "name": "neg", "op": "Neg", "input": [ "add" ], "attr": { "T": { "type": "DT_INT32" } } } ], "library": { }, "versions": { "producer": 134 } }
```

**Comment by Oceania2018** [comment]
@xuwaters Do you know why the fields order are different? The Json serializer randomly pickup property to process? @henon Are you familiar with Newton.Json? It also bothers me when I try to serialize two graphs to comapre difference. @Nucs .

**Comment by xuwaters** [comment]
I think we can just use `EXPECT_EQ(graph_def, graph_def2);` instead of comparing the JSON string.
Since `GraphDef` is generated by protobuf, and implements `IEquatable`, aslo `bool Equals(object other)` has already generated.

**Comment by henon** [comment]
> @henon Are you familiar with Newton.Json? It also bothers me when I try to serialize two graphs to comapre difference.

Yes I am familiar with the problem. You need to order the properties alphabetically when serializing. Here is a link that describes how: https://stackoverflow.com/questions/56933494/how-to-sort-properties-alphabetically-when-serializing-json-using-netwonsoft-lib
