### ISSUE TITLE
ArgumentNullException thrown while trying to run retraining example

### ISSUE THREAD

**Issue by bdeldri** [SciSharp/TensorFlow.NET#605]
I'm trying to run the "Retrain Classifier with InceptionV3" example using TensorFlow.NET v0.20.0-preview3 and SciSharp.TensorFlow.Redist v2.3.0, and I get the following result:

```
8/20/2020 8:18:30 PM Starting Retrain Classifier With InceptionV3
Downloading retrain_images\flower_photos.tgz
.................................................................................................................................................................................................................................................................................................................................................................................................................
Downloaded retrain_images\flower_photos.tgz
Extracting.
.........................
Extracting is completed.
Downloading graph\InceptionV3.meta
......
Downloaded graph\InceptionV3.meta
Downloading retrain_images\tfhub_modules.zip
....................................................................................................................................
Downloaded retrain_images\tfhub_modules.zip
Extracting.
..
Extracting is completed.
Looking for images in 'daisy'
Looking for images in 'dandelion'
Looking for images in 'roses'
Looking for images in 'sunflowers'
Looking for images in 'tulips'
System.ArgumentNullException: Value cannot be null. (Parameter 'key')
   at System.Collections.Generic.Dictionary`2.TryInsert(TKey key, TValue value, InsertionBehavior behavior)
   at System.Collections.Generic.Dictionary`2.set_Item(TKey key, TValue value)
   at Tensorflow.meta_graph.<>c__DisplayClass1_0.<import_scoped_meta_graph_with_return_elements>b__0(IVariableV1 v)
   at System.Collections.Generic.List`1.ForEach(Action`1 action)
   at Tensorflow.meta_graph.import_scoped_meta_graph_with_return_elements(MetaGraphDef meta_graph_or_file, Boolean clear_devices, String import_scope, Dictionary`2 input_map, String unbound_inputs_col_name, String[] return_elements)
   at Tensorflow.saver._import_meta_graph_with_return_elements(String meta_graph_or_file, Boolean clear_devices, String import_scope, String[] return_elements)
   at Tensorflow.tensorflow.train_internal.import_meta_graph(String meta_graph_or_file, Boolean clear_devices, String import_scope)
   at TensorFlowNET.Examples.RetrainClassifierWithInceptionV3.create_module_graph() in C:\dev\SciSharp-Stack-Examples\src\TensorFlowNET.Examples\ImageProcessing\RetrainClassifierWithInceptionV3.cs:line 278
   at TensorFlowNET.Examples.RetrainClassifierWithInceptionV3.ImportGraph() in C:\dev\SciSharp-Stack-Examples\src\TensorFlowNET.Examples\ImageProcessing\RetrainClassifierWithInceptionV3.cs:line 594
   at TensorFlowNET.Examples.RetrainClassifierWithInceptionV3.Train() in C:\dev\SciSharp-Stack-Examples\src\TensorFlowNET.Examples\ImageProcessing\RetrainClassifierWithInceptionV3.cs:line 609
   at TensorFlowNET.Examples.RetrainClassifierWithInceptionV3.Run() in C:\dev\SciSharp-Stack-Examples\src\TensorFlowNET.Examples\ImageProcessing\RetrainClassifierWithInceptionV3.cs:line 96
   at TensorFlowNET.Examples.Program.RunExamples(String key, IExample[] examples) in C:\dev\SciSharp-Stack-Examples\src\TensorFlowNET.Examples\Program.cs:line 87
8/20/2020 8:27:35 PM Completed Retrain Classifier With InceptionV3
Example: Retrain Classifier With InceptionV3 is Failed!
```

Any idea what I am doing wrong here?

**Comment by bdeldri** [comment]
This example does run without errors if I revert back to tensorflow 1.15

**Comment by bdeldri** [comment]
This appears to be a V1/V2 issue with the inception metagraph, not sure if a metagraph is available in the latest version or not.

**Comment by Oceania2018** [comment]
@bdeldri Can you try the latest [preview4](https://www.nuget.org/packages/TensorFlow.NET/0.20.0-preview4) ?
