### ISSUE TITLE
Error NumSharp!!! Please help! Windows 10 C# net core 3.1

### ISSUE THREAD

**Issue by unlimdwl** [SciSharp/TensorFlow.NET#621]
`Fatal error. System.AccessViolationException: Attempted to read or write protected memory. This is often an indication that other memory is corrupt.
   at System.Buffer.Memmove(Byte*, Byte*, UInt64)
   at System.Threading.Tasks.Parallel+<>c__DisplayClass19_0`1[[System.__Canon, System.Private.CoreLib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e]].<ForWorker>b__1(System.Threading.Tasks.RangeWorker ByRef, Int32, Boolean ByRef)
   at System.Threading.Tasks.TaskReplicator+Replica.Execute()
   at System.Threading.ExecutionContext.RunInternal(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object)
   at System.Threading.Tasks.Task.ExecuteWithThreadLocal(System.Threading.Tasks.Task ByRef, System.Threading.Thread)
   at System.Threading.Tasks.ThreadPoolTaskScheduler.TryExecuteTaskInline(System.Threading.Tasks.Task, Boolean)
   at System.Threading.Tasks.TaskScheduler.TryRunInline(System.Threading.Tasks.Task, Boolean)
   at System.Threading.Tasks.Task.InternalRunSynchronously(System.Threading.Tasks.TaskScheduler, Boolean)
   at System.Threading.Tasks.TaskReplicator.Run[[System.Threading.Tasks.RangeWorker, System.Threading.Tasks.Parallel, Version=4.0.4.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a]](ReplicatableUserAction`1<System.Threading.Tasks.RangeWorker>, System.Threading.Tasks.ParallelOptions, Boolean)
   at System.Threading.Tasks.Parallel.ForWorker[[System.__Canon, System.Private.CoreLib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e]](Int32, Int32, System.Threading.Tasks.ParallelOptions, System.Action`1<Int32>, System.Action`2<Int32,System.Threading.Tasks.ParallelLoopState>, System.Func`4<Int32,System.Threading.Tasks.ParallelLoopState,System.__Canon,System.__Canon>, System.Func`1<System.__Canon>, System.Action`1<System.__Canon>)
   at System.Threading.Tasks.Parallel.For(Int32, Int32, System.Action`1<Int32>)
   at NumSharp.NDArray.FetchIndicesND[[System.Single, System.Private.CoreLib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e]](NumSharp.Generic.NDArray`1<Single>, NumSharp.Generic.NDArray`1<Int32>, NumSharp.NDArray[], Int32, Int32[], Int32[], NumSharp.NDArray)
   at NumSharp.NDArray.FetchIndices[[System.Single, System.Private.CoreLib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e]](NumSharp.Generic.NDArray`1<Single>, NumSharp.NDArray[], NumSharp.NDArray, Boolean)
   at NumSharp.NDArray.FetchIndices(System.Object[])
   at Tensorflow._FetchHandler.build_results(Tensorflow.BaseSession, NumSharp.NDArray[])
   at Tensorflow.BaseSession.run(Tensorflow.Tensor, Tensorflow.FeedItem[])
   at CaptchaSolver.TFGraphModel.Predict(NumSharp.NDArray)
   at CaptchaSolver.TableCaptchaSolver.Solve(System.Drawing.Image, System.Drawing.Image)
   at EK_THREAD.Captcha_quest.Captcha_table_vertical_get_answer(HtmlAgilityPack.HtmlDocument)
   at EK_THREAD.Program.Main_thread()
   at System.Threading.ThreadHelper.ThreadStart_Context(System.Object)
   at System.Threading.ExecutionContext.RunInternal(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object)
   at System.Threading.ThreadHelper.ThreadStart()`

**Comment by unlimdwl** [comment]
![изображение](https://user-images.githubusercontent.com/48760384/94350474-54375800-0057-11eb-8712-a804e662c067.png)

**Comment by unlimdwl** [comment]
![изображение](https://user-images.githubusercontent.com/48760384/94350480-62857400-0057-11eb-81b6-80804516761c.png)
![изображение](https://user-images.githubusercontent.com/48760384/94350485-6addaf00-0057-11eb-9367-35cf312dc987.png)
![изображение](https://user-images.githubusercontent.com/48760384/94350491-74ffad80-0057-11eb-9ed7-12d9aed11676.png)

**Comment by Oceania2018** [comment]
Please PR a readable unit test to reproduce this error, otherwise how can we help?

**Comment by unlimdwl** [comment]
![0](https://user-images.githubusercontent.com/48760384/94370080-65837180-00f6-11eb-93ea-a720e4c9862b.png)



[digits_model.zip](https://github.com/SciSharp/TensorFlow.NET/files/5288634/digits_model.zip)


![изображение](https://user-images.githubusercontent.com/48760384/94370112-95327980-00f6-11eb-89c6-eb553459efe9.png)


![изображение](https://user-images.githubusercontent.com/48760384/94370116-a4192c00-00f6-11eb-9e94-bbbedfe36732.png)





`using System.Threading;
using System.Linq;
using NumSharp;
using Tensorflow;
using Tensorflow.Util;
using System.Drawing;
using System.Drawing.Imaging;

namespace SessionRunDemo
{
    class Program
    {
        static void Main(string[] args)
        {
            var graph = new Graph();
            graph.Import("digits_model.pb");
            var session = new Session(graph);
            Tensor inputOperation = graph.First();
            Tensor outputOperation = graph.Last();
            
            for (int i = 0; i < 100; ++i)
            {
                var thread = new Thread(() =>
                {
                    var bitmap = new Bitmap("0.png");
                    while (true)
                    {
                        var arr = RGBImageToNDArray(bitmap).astype(np.float64);
                        arr = np.expand_dims(arr, axis: 0);
                        arr /= 255;

                        // Uncommenting the lock statement prevents the exception from appearing quickly,
                        // however on our actual project we also use the lock and the exception is still
                        // thrown, but it may take around 5 hours after program start to get it
                        //lock (Locks.ProcessWide)
                        {
                            // Using as_default() like this doesn't make any difference
                            //graph.as_default();
                            //session.as_default();
                            session.run(outputOperation, new FeedItem(inputOperation, arr));
                        }
                    }

                });
                thread.Start();
            }

            while (true)
            {
                Thread.Sleep(1000);
            }
        }

        // GetBitmapBytes() implemetation by Nucs:
        // https://github.com/SciSharp/NumSharp/issues/289#issuecomment-520626604
        public static NDArray RGBImageToNDArray(Image image)
        {
            Bitmap bitmap = image as Bitmap;

            BitmapData bmpData = bitmap.LockBits(new Rectangle(0, 0, bitmap.Width, bitmap.Height), ImageLockMode.ReadOnly, bitmap.PixelFormat);
            try
            {
                unsafe
                {
                    // Create a 1d vector without filling it's values to zero (similar to np.empty)
                    var array = new NDArray(NPTypeCode.Byte, Shape.Vector(bmpData.Stride * bitmap.Height), fillZeros: false);

                    // Get the respective addresses
                    byte* src = (byte*)bmpData.Scan0;
                    // we can use unsafe because we just allocated that array and we know for sure it is contagious
                    byte* dst = (byte*)array.Unsafe.Address;

                    // Copy the RGB values into the array.
                    System.Buffer.MemoryCopy(src, dst, array.size, array.size);

                    // In the source array colors order is inverted (BGR), so -1 is used as the step value for the colors
                    // dimension to fix their order
                    return array.reshape(bitmap.Height, bitmap.Width, -1)[":, :, 2::-1"];
                }
            }
            finally
            {
                bitmap.UnlockBits(bmpData);
            }
        }
    }
}
`

**Comment by Oceania2018** [comment]
Graph and Session are not thread safe class, you can't do it in multiple threads.
