### ISSUE TITLE
Exception in example 21

### ISSUE THREAD

**Issue by ekleiman22** [SciSharp/TensorFlow.NET#672]
I downloaded yours TensorFlowNET.Examples and try to check all examples. In example #21 I get the following exception:
Tensorflow.InvalidArgumentError: You must feed a value for placeholder tensor 'conv2d/ReadVariableOp/resource' with dtype resource
         [[{{node conv2d/ReadVariableOp/resource}}]]
   at Tensorflow.BaseSession._call_tf_sessionrun(KeyValuePair`2[] feed_dict, TF_Output[] fetch_list, List`1 target_list)
   at Tensorflow.BaseSession._do_run(List`1 target_list, List`1 fetch_list, Dictionary`2 feed_dict)
   at Tensorflow.BaseSession._run(Object fetches, FeedItem[] feed_dict)
   at Tensorflow.BaseSession.run(ValueTuple`3 fetches, FeedItem[] feed_dict)
   at TensorFlowNET.Examples.CnnTextClassification.Train() in C:\Users\eug10\source\repos\SciSharp-Stack-Examples-master\src\TensorFlowNET.Examples\TextProcessing\CnnTextClassification.cs:line 230
   at TensorFlowNET.Examples.CnnTextClassification.Run() in C:\Users\eug10\source\repos\SciSharp-Stack-Examples-master\src\TensorFlowNET.Examples\TextProcessing\CnnTextClassification.cs:line 75
   at TensorFlowNET.Examples.Program.RunExamples(String key, IExample[] examples) in C:\Users\eug10\source\repos\SciSharp-Stack-Examples-master\src\TensorFlowNET.Examples\Program.cs:line 87

**Comment by Oceania2018** [comment]
@ekleiman22 It's been fixed.

![image](https://user-images.githubusercontent.com/1705364/101998934-5fd10d00-3c9d-11eb-95f9-81d797f0b2f3.png)
