### ISSUE TITLE
model.fit Tensorflow.InvalidArgumentError

### ISSUE THREAD

**Issue by TrueGameover** [SciSharp/TensorFlow.NET#737]
```
Unhandled exception. Tensorflow.InvalidArgumentError: Input 'resource' passed int64_ref expected resource while building NodeDef 'Read/ReadVariableOp' using Op<name=ReadVariableOp; signature=resource:resource -> value:dtype; attr=dtype:type; is_stateful=true>
   at Tensorflow.ops._create_c_op(Graph graph, NodeDef node_def, Tensor[] inputs, Operation[] control_inputs, OpDef op_def)
   at Tensorflow.Operation..ctor(NodeDef node_def, Graph g, Tensor[] inputs, TF_DataType[] output_types, ITensorOrOperation[] control_inputs, TF_DataType[] input_types, String original_op, OpDef op_def)
   at Tensorflow.Graph.create_op(String op_type, Tensor[] inputs, TF_DataType[] dtypes, TF_DataType[] input_types, String name, Dictionary`2 attrs, OpDef op_def, Boolean compute_device)
   at Tensorflow.OpDefLibrary.<>c__DisplayClass1_0.<_apply_op_helper>b__0(NameScope scope)
   at Tensorflow.Binding.tf_with[TIn,TOut](TIn py, Func`2 action)
   at Tensorflow.OpDefLibrary._apply_op_helper(String op_type_name, String name, Dictionary`2 keywords)
   at Tensorflow.OpDefLibrary._apply_op_helper(String op_type_name, String name, Object args)
   at Tensorflow.gen_resource_variable_ops.read_variable_op(Tensor resource, TF_DataType dtype, String name)
   at Tensorflow.BaseResourceVariable._read_variable_op()
   at Tensorflow.BaseResourceVariable.<read_value>b__53_0(NameScope <p0>)
   at Tensorflow.Binding.tf_with[TIn,TOut](TIn py, Func`2 action)
   at Tensorflow.BaseResourceVariable.read_value()
   at Tensorflow.BaseResourceVariable.numpy()
   at Tensorflow.Keras.Engine.DataAdapters.DataHandler..ctor(DataHandlerArgs args)
   at Tensorflow.Keras.Engine.Model.fit(NDArray x, NDArray y, Int32 batch_size, Int32 epochs, Int32 verbose, Single validation_split, Boolean shuffle, Int32 initial_epoch, Int32 max_queue_size, Int32 workers, Boolean use_multiprocessing)
   at TensorFlowTest1.Program.Main(String[] args) in /home/***/TensorFlowTest1/TensorFlowTest1/Program.cs:line 24
```
from nuget:
TensorFlow.NET 0.32.0
TensorFlow.Keras 0.3.0
SciSharp.TensorFlow.Redist 2.3.1

OS: debian

```
dotnet --version
5.0.102
```

```
using System;
using System.Collections.Generic;
using NumSharp;
using Tensorflow;
using Tensorflow.Keras;
using Tensorflow.Keras.Losses;
using static Tensorflow.Binding;

****
           tf.compat.v1.disable_eager_execution();// without it hangs indefinitely on .fit method
            var celsius = np.array(new int[] {-40, -10, 0, 8, 15, 22, 38});
            var fahrenheit = np.array(new int[] {-40, 14, 32, 46, 59, 72, 100});

            var layer0 = KerasApi.keras.layers.Dense(1);
            var model = KerasApi.keras.Sequential(new List<ILayer>() {layer0});

            model.compile(new MeanSquaredError(), KerasApi.keras.optimizers.Adam(0.1f), Array.Empty<string>());
            model.fit(celsius, fahrenheit);
```

**Comment by Oceania2018** [comment]
Please try [latest version](https://www.nuget.org/packages/TensorFlow.Keras/).

**Comment by TrueGameover** [comment]
TensorFlow.NET 0.33.0
TensorFlow.Keras 0.4.0
SciSharp.TensorFlow.Redist 2.4.0

```
using System;
using System.Collections.Generic;
using NumSharp;
using Tensorflow;
using Tensorflow.Keras;
using Tensorflow.Keras.Losses;
using static Tensorflow.Binding;

****
            var celsius = np.array(new int[] {-40, -10, 0, 8, 15, 22, 38});
            var fahrenheit = np.array(new int[] {-40, 14, 32, 46, 59, 72, 100});

            var layer0 = KerasApi.keras.layers.Dense(1);
            var model = KerasApi.keras.Sequential(new List<ILayer>() {layer0});

            model.compile(new MeanSquaredError(), KerasApi.keras.optimizers.Adam(0.1f), Array.Empty<string>());
            model.fit(celsius, fahrenheit);
```

Log:

```
2021-02-07 19:09:14.330704: I tensorflow/core/platform/cpu_feature_guard.cc:142] This TensorFlow binary is optimized with oneAPI Deep Neural Network Library (oneDNN) to use the following CPU instructions in performance-critical operations:  AVX2 FMA
To enable them in other operations, rebuild TensorFlow with the appropriate compiler flags.
Unhandled exception. System.EntryPointNotFoundException: Unable to find an entry point named 'TF_StringEncodedSize' in shared library 'tensorflow'.
   at Tensorflow.c_api.TF_StringEncodedSize(UInt64 len)
   at Tensorflow.Tensor.StringTensor(Byte[][] buffer, TensorShape shape)
   at Tensorflow.Tensor..ctor(String[] strings)
   at Tensorflow.Eager.EagerTensor..ctor(String[] value, String device_name)
   at Tensorflow.constant_op.convert_to_eager_tensor(Object value, Context ctx, TF_DataType dtype)
   at Tensorflow.constant_op._constant_impl(Object value, TF_DataType dtype, TensorShape shape, String name, Boolean verify_shape, Boolean allow_broadcast)
   at Tensorflow.constant_op.constant(Object value, TF_DataType dtype, Int32[] shape, String name)
   at Tensorflow.ops.convert_to_tensor(Object value, TF_DataType dtype, String name, Boolean as_ref, TF_DataType preferred_dtype, Context ctx)
   at Tensorflow.tensorflow.convert_to_tensor(Object value, TF_DataType dtype, String name, TF_DataType preferred_dtype)
   at Tensorflow.OptimizeDataset..ctor(IDatasetV2 dataset, String[] optimizations, String[] optimization_configs)
   at Tensorflow.DatasetV2.optimize(String[] optimizations, String[] optimization_configs)
   at Tensorflow.DatasetV2.apply_options()
   at Tensorflow.OwnedIterator._create_iterator(IDatasetV2 dataset)
   at Tensorflow.Keras.Engine.DataAdapters.DataHandler.enumerate_epochs()+MoveNext()
   at Tensorflow.Keras.Engine.Model.FitInternal(Int32 epochs, Int32 verbose)
   at Tensorflow.Keras.Engine.Model.fit(NDArray x, NDArray y, Int32 batch_size, Int32 epochs, Int32 verbose, Single validation_split, Boolean shuffle, Int32 initial_epoch, Int32 max_queue_size, Int32 workers, Boolean use_multiprocessing)
   at TensorFlowTest1.Program.Main(String[] args) in /home/***/RiderProjects/TensorFlowTest1/TensorFlowTest1/Program.cs:line 25
```

**Comment by Oceania2018** [comment]
Please install [v2.3.1](https://www.nuget.org/packages/SciSharp.TensorFlow.Redist/2.3.1).
