### ISSUE TITLE
System.AccessViolationException: Attempted to read or write protected memory. This is often an indication that other memory is corrupt

### ISSUE THREAD

**Issue by Inzta** [SciSharp/TensorFlow.NET#742]
I saw that the issue was addressed somewhat in issue #380. But after adjusting to the comments there, I still see the issue.
So here goes...

I run TensorFlow.net (0.15.1) using SciSharp.TensorFlow.Redist (2.1.0) in a multi-threaded environment in .NET Framework 4.8.
I am unable to reproduce the error locally, but have seen the error multiple times on my test setup running on a Windows Server 2008 R2 and also Windows Server 2016.

I have a single threaded project running on these test PCs as well, without any errors.

Stack trace:

> 2021-02-01 16:16:34.438 +01:00 [ERR] Unhandled exception
System.AccessViolationException: Attempted to read or write protected memory. This is often an indication that other memory is corrupt.
   at NumSharp.NDArray.<>c__DisplayClass316_2`1.<FetchIndices>b__3(Int32 i)
   at System.Threading.Tasks.Parallel.<>c__DisplayClass17_0`1.<ForWorker>b__1()
   at System.Threading.Tasks.Task.InnerInvokeWithArg(Task childTask)
   at System.Threading.Tasks.Task.<>c__DisplayClass176_0.<ExecuteSelfReplicating>b__0(Object <p0>)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.Tasks.Task.ExecuteWithThreadLocal(Task& currentTaskSlot)
   at System.Threading.Tasks.Task.ExecuteEntry(Boolean bPreventDoubleExecution)
   at System.Threading.Tasks.ThreadPoolTaskScheduler.TryExecuteTaskInline(Task task, Boolean taskWasPreviouslyQueued)
   at System.Threading.Tasks.TaskScheduler.TryRunInline(Task task, Boolean taskWasPreviouslyQueued)
   at System.Threading.Tasks.Task.InternalRunSynchronously(TaskScheduler scheduler, Boolean waitForCompletion)
   at System.Threading.Tasks.Parallel.ForWorker[TLocal](Int32 fromInclusive, Int32 toExclusive, ParallelOptions parallelOptions, Action`1 body, Action`2 bodyWithState, Func`4 bodyWithLocal, Func`1 localInit, Action`1 localFinally)
   at System.Threading.Tasks.Parallel.For(Int32 fromInclusive, Int32 toExclusive, Action`1 body)
   at NumSharp.NDArray.FetchIndices[T](NDArray`1 source, NDArray[] indices, NDArray out, Boolean extraDim)
   at NumSharp.NDArray.FetchIndices(Object[] indicesObjects)
   at Tensorflow._FetchHandler.build_results(BaseSession session, NDArray[] tensor_values)
   at ES.Air.Engine.Cropper.GetCrop(ProcessingImage stack, CropData& cropData)
   at ES.Air.Engine.ClassificationManager.OnProcess(ProcessingImage queueItem)
   at ES.Air.Engine.QueueHandlerBase`1.Execute()
   at System.Threading.Tasks.Task.Execute()
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.Tasks.Task.ExecuteWithThreadLocal(Task& currentTaskSlot)
   at System.Threading.Tasks.Task.ExecuteEntry(Boolean bPreventDoubleExecution)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.ThreadHelper.ThreadStart(Object obj)

The models are all loaded on the main thread. Some models run on a classifier thread, and some run on an estimation thread.
These threads are started the following way: `Task.Factory.StartNew(thread.Execute, TaskCreationOptions.LongRunning);`

The code for loading and initializing a model:
```C#
_graph = new Graph();
_graph.as_default();
_graph.Import(ModelPath);

foreach (var operation in _inputOperations)
    AddInputOperation(operation);

foreach (var operation in _outputOperations)
    OutputOperations.Add(_graph.OperationByName(operation));

var gpuOptions = new GPUOptions {PerProcessGpuMemoryFraction = 0.01, AllowGrowth = true};

var graphOptions = new GraphOptions
{
    OptimizerOptions = new OptimizerOptions
        {
            OptLevel = OptimizerOptions.Types.Level.L1,
            DoFunctionInlining = true,
            DoConstantFolding = true,
            DoCommonSubexpressionElimination = true,
            GlobalJitLevel = OptimizerOptions.Types.GlobalJitLevel.On1
        }
};

var configProto = new ConfigProto
{
    InterOpParallelismThreads = _coresToUse,
    IntraOpParallelismThreads = _coresToUse,
    AllowSoftPlacement = true,
    GpuOptions = gpuOptions,
    GraphOptions = graphOptions
};

Status = new Status();
Session = new Session(_graph, configProto, Status);
Session.as_default();
```

Each model initializes a Session and calls Session.Run:
```C#
Session.graph.as_default();

// input tensor {1, 128, 128, 1}
var inputTensor = new Tensor(stack.ImageData, new long[] {1, stack.Height, stack.Height, stack.FocalPlanes});

var result = Session.run(OutputOperations.Select(o => o.outputs[0]).ToArray(), new FeedItem(InputOperations[0].outputs[0], inputTensor));

// free tensor
inputTensor.Dispose();
```

Before using the Tensor as input I used NumSharps NDArray as input. This resulted in my app crashing at every run, also locally.
The only way to fix this, at the time, was to disable GarbageCollection when calling Session.run, using GC.TryStartNoGCRegion and GC.EndNoGCRegion. This resulted in a large memory usage during the run, but I did not see the error.

It seemed that the input were collected while the Session.run was called, and I though that the tensor being disposable, it would fix the issue.

Where do I go from here?
Let me know if I should provide anything else.

**Comment by Oceania2018** [comment]
@Inzta Thanks for describing issue so detail. It's very helpful, if you can PR a minimal code snippet of unit test [here ](https://github.com/SciSharp/TensorFlow.NET/blob/master/test/TensorFlowNET.UnitTest/MultithreadingTests.cs), we can look into it immediately.

By the way, we're always focus on latest version, don't have spare time to maintain legacy versions.
