### ISSUE TITLE
keras.preprocessing.image_dataset_from_directory fails with ValueError

### ISSUE THREAD

**Issue by oluwandabira** [SciSharp/TensorFlow.NET#817]
Attempting to run the script
```fsharp
// image_dataset_test.fsx
#r "nuget: TensorFlow.NET"
#r "nuget: TensorFlow.Keras"
#r "nuget: SciSharp.TensorFlow.Redist"

open System.IO

open Tensorflow.Keras.Utils
open type Tensorflow.KerasApi

let data_dir =
    let fileName = "flower_photos.tgz"
    let url = $"https://storage.googleapis.com/download.tensorflow.org/example_images/flower_photos.tgz"
    let data_dir = Path.Combine(Path.GetTempPath(), "flower_photos")
    Web.Download(url, data_dir, fileName) |> ignore
    Compress.ExtractTGZ(Path.Join(data_dir, fileName), data_dir)
    Path.Combine(data_dir, "flower_photos")

let dataset = keras.preprocessing.image_dataset_from_directory(data_dir)
printf "%A\n" (dataset.class_names)
```

fails with
```
/tmp/flower_photos/flower_photos.tgz already exists.
Found 3670 files belonging to 5 classes.
2021-06-18 02:38:42.496684: I tensorflow/core/platform/cpu_feature_guard.cc:142] This TensorFlow binary is optimized with oneAPI Deep Neural Network Library (oneDNN) to use the following CPU instructions in performance-critical operations:  AVX2 FMA
To enable them in other operations, rebuild TensorFlow with the appropriate compiler flags.
Tensorflow.ValueError: None values not supported.
   at Tensorflow.tensor_util.make_tensor_proto(Object values, TF_DataType dtype, Int32[] shape, Boolean verify_shape, Boolean allow_broadcast)
   at Tensorflow.constant_op._constant_impl(Object value, TF_DataType dtype, TensorShape shape, String name, Boolean verify_shape, Boolean allow_broadcast)
   at Tensorflow.constant_op.constant(Object value, TF_DataType dtype, Int32[] shape, String name)
   at Tensorflow.ops.convert_to_tensor(Object value, TF_DataType dtype, String name, Boolean as_ref, TF_DataType preferred_dtype, Context ctx)
   at Tensorflow.image_ops_impl.resize_images_v2[T](Tensor images, T size, String method, Boolean preserve_aspect_ratio, Boolean antialias, String name)
   at Tensorflow.tensorflow.image_internal.resize_images_v2(Tensor images, TensorShape size, String method, Boolean preserve_aspect_ratio, Boolean antialias, String name)
   at Tensorflow.Keras.Preprocessing.path_to_image(Tensor path, TensorShape image_size, Int32 num_channels, String interpolation)
   at Tensorflow.Keras.Preprocessing.<>c__DisplayClass11_0.<paths_and_labels_to_dataset>b__0(Tensors x)
   at Tensorflow.MapDataset..ctor(IDatasetV2 input_dataset, Func`2 map_func, Boolean use_inter_op_parallelism, Boolean preserve_cardinality, Boolean use_legacy_function)
   at Tensorflow.DatasetV2.map(Func`2 map_func, Boolean use_inter_op_parallelism, Boolean preserve_cardinality, Boolean use_legacy_function)
   at Tensorflow.Keras.Preprocessing.paths_and_labels_to_dataset(String[] image_paths, TensorShape image_size, Int32 num_channels, Int32[] labels, String label_mode, Int32 num_classes, String interpolation)
   at Tensorflow.Keras.Preprocessing.image_dataset_from_directory(String directory, String labels, String label_mode, String[] class_names, String color_mode, Int32 batch_size, TensorShape image_size, Boolean shuffle, Nullable`1 seed, Single validation_split, String subset, String interpolation, Boolean follow_links)
   at <StartupCode$FSI_0002>.$FSI_0002.main@()
Stopped due to error
```

I've also tried putting similar code into a project and got the same result.

**Comment by Oceania2018** [comment]
Should have been fixed in latest version.
