### ISSUE TITLE
Model.save_weights broken in the latest version

### ISSUE THREAD

**Issue by ginnyliou** [SciSharp/TensorFlow.NET#835]
Model.save_weights throw the following exception under the latest packages (Tensorflow.Net v0.60.0, and Tensorflow.Keras v0.6.0)

```
Unhandled exception. System.NotImplementedException
   at Tensorflow.NumPy.NDArray.ToMuliDimArray[T]()
   at Tensorflow.Keras.Saving.hdf5_format.WriteDataset(Int64 f, String name, Tensor data)
   at Tensorflow.Keras.Saving.hdf5_format.save_weights_to_hdf5_group(Int64 f, List`1 layers)
   at Tensorflow.Keras.Engine.Model.save_weights(String filepath, Boolean overwrite, String save_format, Object options)
```

Note: v0.40.1 and v0.5.1 works.

**Comment by Oceania2018** [comment]
fixed in v0.60.1, will release soon.
