### ISSUE TITLE
model.load_weights freezes on linux machines

### ISSUE THREAD

**Issue by Licho1** [SciSharp/TensorFlow.NET#859]
It works fine on windows, but on linux (tested on AWS EC2 instance) model.load_weights never completes despite having correct permissions and path to weights.

**Comment by Licho1** [comment]
After adding global lock, I get a visible exception:
```
Unhandled exception. System.TypeInitializationException: The type initializer for 'HDF.PInvoke.H5F' threw an exception.
 ---> System.DllNotFoundException: Unable to load shared library 'hdf5' or one of its dependencies. In order to help diagnose loading problems, consider setting the LD_DEBUG environment variable: libhdf5: cannot open shared object file: No such file or directory
   at HDF.PInvoke.H5.open()
   at HDF.PInvoke.H5F..cctor() in /home/appveyor/projects/hdf-pinvoke-1-10/submodules/HDF.PInvoke/HDF5/H5Fpublic.cs:line 41
   --- End of inner exception stack trace ---
   at HDF.PInvoke.H5F.open(String filename, UInt32 flags, Int64 plist)
   at HDF5CSharp.Hdf5.OpenFile(String filename, Boolean readOnly)
   at Tensorflow.Keras.Engine.Model.load_weights(String filepath, Boolean by_name, Boolean skip_mismatch, Object options)

```

**Comment by Licho1** [comment]
Fixeable by copying native libhdf libraries from runtime folder to the bin folder. Likely bug in HDF itself
