### ISSUE TITLE
Exception after upgrade TensorFlow.NET form 0.60.4 to 0.60.5

### ISSUE THREAD

**Issue by Tomazzzzz** [SciSharp/TensorFlow.NET#886]
Message: 
System.Exception : make_tensor_proto Not Implemented

  Stack Trace: 
tensor_util.make_tensor_proto(Object values, TF_DataType dtype, Shape shape, Boolean verify_shape, Boolean allow_broadcast)
constant_op.convert_to_graph_tensor(Object value, TF_DataType dtype, Shape shape, String name, Boolean verify_shape, Boolean allow_broadcast)
constant_op.constant(Object value, TF_DataType dtype, Shape shape, Boolean verify_shape, Boolean allow_broadcast, String name)
Shape.op_Implicit(Shape shape)
array_ops.fill[T](Shape dims, T value, String name)
<>c__DisplayClass23_0.<ones>b__0(NameScope scope)
Binding.tf_with[TIn,TOut](TIn py, Func`2 action)
array_ops.ones(Shape shape, TF_DataType dtype, String name)
tensorflow.ones(Shape shape, TF_DataType dtype, String name)
TensorFlowForexTrainEngineAbstract.CreateLayerBn(String layerName, Tensor inputTensor, Int32 inputCount, Int32 outputCount) line 511
AdamExtendedBn1200V2.CreateGraph() line 29
TensorFlowForexTrainEngineAbstract.BuildGraph(String modelPath) line 392
TensorFlow.Build_AdamExtendedBn1200V2() line 490

**Comment by Tomazzzzz** [comment]
I will do it ASAP.

**Comment by Tomazzzzz** [comment]
Hello, this code fails after update.

```
using System;
using static Tensorflow.Binding;
namespace BugTest
{
    class Program
    {
        static void Main(string[] args)
        {
            try
            {
                using (var graph = tf.Graph().as_default())
                {
                    //fails on this line  System.Exception : make_tensor_proto Not Implemented
                    var gamma = tf.Variable(tf.ones(100), name: "gamma");
                    var beta = tf.Variable(tf.zeros(100), name: "beta");
                }
            }
            catch (Exception e)
            {
                Console.WriteLine(e);
            }
        }
    }
}

```

System.Exception: make_tensor_proto Not Implemented
   at Tensorflow.tensor_util.make_tensor_proto(Object values, TF_DataType dtype, Shape shape, Boolean verify_shape, Boolean allow_broadcast)
   at Tensorflow.constant_op.convert_to_graph_tensor(Object value, TF_DataType dtype, Shape shape, String name, Boolean verify_shape, Boolean allow_broadcast)
   at Tensorflow.constant_op.constant(Object value, TF_DataType dtype, Shape shape, Boolean verify_shape, Boolean allow_broadcast, String name)
   at Tensorflow.Shape.op_Implicit(Shape shape)
   at Tensorflow.array_ops.fill[T](Shape dims, T value, String name)
   at Tensorflow.array_ops.<>c__DisplayClass23_0.<ones>b__0(NameScope scope)
   at Tensorflow.Binding.tf_with[TIn,TOut](TIn py, Func`2 action)
   at Tensorflow.array_ops.ones(Shape shape, TF_DataType dtype, String name)
   at Tensorflow.tensorflow.ones(Shape shape, TF_DataType dtype, String name)
   at BugTest.Program.Main(String[] args) in E:\Projects\NueralNetwork\BugTest\Program.cs:line 15

**Comment by Oceania2018** [comment]
Fixed for next release.
