### ISSUE TITLE
disable_eager_execution with keras.Model fail

### ISSUE THREAD

**Issue by dice2019** [SciSharp/TensorFlow.NET#899]
hi, when i want to disable eager mode and use keras  module:
```
 tf.compat.v1.disable_eager_execution();
...
keras.Model(inputs, outputs, "name");
```
however, it turns out throw a exception
```
ystem.NullReferenceException: Object reference not set to an instance of an object.
   at Tensorflow.Graphs.SubGraphUtility.lift_to_graph(Tensors init_tensors, FuncGraph graph, List`1 sources, Boolean add_sources, Boolean handle_captures, Graph base_graph, Dictionary`2 op_map)
   at Tensorflow.Keras.BackendImpl.eval_in_eager_or_function(Tensors outputs)
   at Tensorflow.Keras.Utils.base_layer_utils.<>c__DisplayClass5_1.<CreateKerasHistoryHelper>b__0(NameScope <p0>)
   at Tensorflow.Binding.tf_with[T](T py, Action`1 action)
   at Tensorflow.Keras.Utils.base_layer_utils.CreateKerasHistoryHelper(Tensors tensors, List`1 processed_ops, List`1 created_layers)
   at Tensorflow.Keras.Utils.base_layer_utils.CreateKerasHistoryHelper(Tensors tensors, List`1 processed_ops, List`1 created_layers)
   at Tensorflow.Keras.Utils.base_layer_utils.create_keras_history(Tensors inputs)
   at Tensorflow.Keras.Engine.Functional._init_graph_network(Tensors inputs, Tensors outputs)
   at Tensorflow.Keras.Engine.Functional..ctor(Tensors inputs, Tensors outputs, String name)
   at Tensorflow.Keras.KerasInterface.Model(Tensors inputs, Tensors outputs, String name)

```
so i check out soure code, and found that in "src\TensorFlowNET.Core\Graphs\SubGraphUtility.cs"
```
            // When lifting from one FuncGraph to another, we will need to capture the
            // relevant tensors as well.
            var inverse_captures = new Dictionary<Tensor, Tensor>();
            Tensor[] internal_captures = null;
            if (base_graph is FuncGraph base_func_graph)
            {
                var captures = base_func_graph.captures;
                foreach (var (external_capture, internal_capture) in captures)
                    inverse_captures[internal_capture] = external_capture;
                internal_captures = base_func_graph.internal_captures;
            }

            graph.as_default();
            var source_ops = new List<Operation>();
            // Add the sources in the same order as the original graph.
            foreach (var s in internal_captures)
            {
                if (sources.Contains(s))
                {
                    sources.Remove(s);
                    source_ops.Add(s.op);
                    _copy_source(s: s,
                        graph: graph,
                        op_map: op_map,
                        handle_captures: handle_captures,
                        inverse_captures: inverse_captures,
                        base_graph: base_graph);
                }
            }
```
In fact, the var "base_graph" is not "FuncGraph", so the "internal_captures" still null. 
So is that a bug or something wrong ?

**Comment by Oceania2018** [comment]
It doesn't need to `tf.compat.v1.disable_eager_execution()` in keras.

**Comment by dice2019** [comment]
In that case, the tensorflow.net in eager mode which is slow significantly. because not use gpu to do that.

**Comment by Oceania2018** [comment]
I'm not really understand. As I know, the GPU usage has nothing to do with eager mode or not.

**Comment by dice2019** [comment]
I thought in eager mode, the tensorflow.net just use cpu to do the predict, is that right ? I found that by dotTrace(jetbrains tool)

**Comment by Oceania2018** [comment]
It depends on which version you installed [CPU ](https://www.nuget.org/packages/SciSharp.TensorFlow.Redist-Windows-GPU/)or [GPU](https://www.nuget.org/packages/SciSharp.TensorFlow.Redist-Windows-GPU/)
