### ISSUE TITLE
Out of Memory Error

### ISSUE THREAD

**Issue by santoshkc** [SciSharp/TensorFlow.NET#904]
Hi,
I am new to tensorflow and was trying Tensorflow.NET to run classification example(Keras.NET example) in cifar10 dataset on NVIDIA GPU 1050(2 GB). However, I am getting out of memory error:
2022-01-08 20:21:27.378152: W tensorflow/core/framework/op_kernel.cc:1733] RESOURCE_EXHAUSTED: failed to allocate memory
Unhandled exception. Tensorflow.TensorflowException: failed to allocate memory
   at Tensorflow.Eager.EagerRunner.TFE_FastPathExecute(FastPathOpExecInfo op_exec_info)
   at Tensorflow.Contexts.Context.ExecEagerAction(String OpType, String Name, ExecuteOpArgs args)      
   at Tensorflow.Contexts.Context.ExecuteOp(String opType, String name, ExecuteOpArgs args)
   at Tensorflow.gen_math_ops.cast(Tensor x, TF_DataType DstT, Boolean Truncate, String name)
   
I have tried following without any success:

- tf.compat.v1.disable_eager_execution();

- tf.config.experimental.set_memory_growth(gpu, True)
- set environmental variable TF_GPU_ALLOCATOR to cuda_malloc_async

Tensorflow documentation also mentions about virtual device configuration.However, I could not find way to experiment with that:
    tf.config.set_logical_device_configuration(
        gpus[0],
        [tf.config.LogicalDeviceConfiguration(memory_limit=1024)])

Is there way to setup logical device configuration?

**Comment by Oceania2018** [comment]
Please increase your GPU phsical memory.
.NET will use more GPU memory compared to python.
