### ISSUE TITLE
Model.summary() throws exceptions.

### ISSUE THREAD

**Issue by TheBlackPlague** [SciSharp/TensorFlow.NET#930]
Hello,

I'm trying to translate a very basic model from Python to C#.

```cs
using System;
using System.Collections.Generic;
using Tensorflow;
using Tensorflow.Keras;
using Tensorflow.Keras.Datasets;
using Tensorflow.Keras.Engine;
using Tensorflow.Keras.Losses;
using Tensorflow.Keras.Optimizers;
using Tensorflow.NumPy;
using static Tensorflow.Binding;
using static Tensorflow.KerasApi;

namespace TFLearnNET
{

    internal static class NnTask
    {

        private static string[] LabelNames = new[]
        {
            "Top", "Bottom", "Pullover",
            "Dress", "Coat", "Sandal",
            "Dress Shirt", "Sneaker",
            "Bag", "Ankle Boot"
        };

        private static NDArray TrainingFeatures;
        private static NDArray TrainingLabels;
        private static NDArray TestingFeatures;
        private static NDArray TestingLabels;

        private static Sequential Model;

        public static void Run()
        {
            PreprocessData();
            BuildModel();
            TrainModel();
        }

        private static void PreprocessData()
        {
            Console.WriteLine("Getting dataset...");
            DatasetPass mnist = keras.datasets.mnist.load_data();
            Console.WriteLine("Dataset found and obtained.");
            
            (NDArray trainingFeaturesUnprocessed, NDArray trainingLabelsUnprocessed) = mnist.Train;
            TrainingLabels = trainingLabelsUnprocessed;
            Console.WriteLine("Training pointers set...");
            Console.WriteLine("Training unprocessed input shape: " + trainingFeaturesUnprocessed.shape);

            (NDArray testingFeaturesUnprocessed, NDArray testingLabelsUnprocessed) = mnist.Test;
            TestingLabels = testingLabelsUnprocessed;
            Console.WriteLine("Testing pointers set...");
            Console.WriteLine("Testing unprocessed input shape: " + testingFeaturesUnprocessed.shape);
            
            Console.WriteLine("Preprocessing data...");
            
            Console.WriteLine("Normalizing data scale [0, 255] to [0, 1].");
            TrainingFeatures = trainingFeaturesUnprocessed / 255;
            TestingFeatures = testingFeaturesUnprocessed / 255;
            
            Console.WriteLine("Preprocess completed.");
            Console.WriteLine("Training input shape: " + TrainingFeatures.shape);
            Console.WriteLine("Testing input shape: " + TestingFeatures.shape);
        }

        private static void BuildModel()
        {
            Console.WriteLine("Defining model layers...");
            List<ILayer> layers = new(new[]
            {
                // Flattens the input to 784 neurons.
                keras.layers.Flatten(),
                
                // Dense just means all neurons from previous
                // layer are connected to this layer too.
                // The number 128 is arbitrary - usually, you'd
                // want this number to be less than input neurons
                // but more than output neurons.
                // ReLU: x < 0 => y = 0 || x >= 0 => y = x
                (Layer) keras.layers.Dense(128, "relu", 784),
                
                // Dense just means all neurons from previous
                // layer are connected to this layer too.
                // Layer size is based on how many classes we have.
                // Softmax: sigma(layer) = 1
                keras.layers.Dense(LabelNames.Length, "softmax", 128)
            });
            Console.WriteLine("Model Layers defined.");
            
            Console.WriteLine("Building and compiling model...");
            Model = keras.Sequential(layers, "Fashion-Cloth-Classifier");
            Model.compile(
                new Adam(), 
                new SparseCategoricalCrossentropy(), 
                new []{"accuracy"}
            );
            Console.WriteLine("Model compiled ---- ");
            Model.summary();
        }

        private static void TrainModel()
        {
            NDArray castedFeatures = tf.cast(TrainingFeatures, TF_DataType.TF_FLOAT).numpy();
            Model.fit(castedFeatures, TrainingLabels, 1, 10);
        }

    }

}
```

This same code in Python looks like so: 
```py
def nn_task():
    mnist = keras.datasets.fashion_mnist
    # (60K, 28, 28), [0, 0, 0] = 0  ---- 0: Black, 255: White
    (train_features, train_labels), (test_features, test_labels) = mnist.load_data()
    print(train_features.shape)
    label_names = [
        "Top", "Bottom", "Pullover",
        "Dress", "Coat", "Sandal",
        "Dress Shirt", "Sneaker",
        "Bag", "Ankle Boot"
    ]

    # plt.figure()
    # plt.imshow(train_features[0])
    # plt.colorbar()
    # plt.gray()
    # plt.plot()
    # plt.pause(5)

    # Normalize to scale of [0, 1]
    # Ensures that values only range from 0 to 1.
    train_features = train_features / 255
    test_features = test_features / 255

    model = keras.Sequential([
        # Flattens the input to 784 neurons.
        keras.layers.Flatten(input_shape=(28, 28), name="Input"),

        # Dense just means all neurons from previous
        # layer are connected to this layer too.
        # The number 128 is arbitrary - usually, you'd
        # want this number to be less than input neurons
        # but more than output neurons.
        # ReLU: x < 0 => y = 0 || x >= 0 => y = x
        keras.layers.Dense(128, activation="relu", name="DataParser"),

        # Dense just means all neurons from previous
        # layer are connected to this layer too.
        # Layer size is based on how many classes we have.
        # Softmax: sigma(layer) = 1
        keras.layers.Dense(len(label_names), activation="softmax", name="Output")
    ], "Fashion-Cloth-Classifier")

    model.compile(
        optimizer="adam",
        loss="sparse_categorical_crossentropy", 
        metrics=["accuracy"]
    )
    model.summary()

    with tf.device("/GPU:0"):
        model.fit(train_features, train_labels, epochs=10, batch_size=1, callbacks=[board_callback])
        
```

I'm quite unsure of why this doesn't work. Any assistance would be helpful.

The exception thrown is: 

Model.summary():
```
Unhandled exception. System.ArgumentOutOfRangeException: Index was out of range. Must be non-negative and less than the size of the collection. (Parameter 'index')
   at System.Collections.Generic.List`1.get_Item(Int32 index)
   at Tensorflow.Keras.Engine.Layer.get_output_shape()
   at Tensorflow.Keras.Utils.layer_utils.print_layer_summary(ILayer layer, Int32[] positions)
   at Tensorflow.Keras.Utils.layer_utils.print_summary(Model model, Int32 line_length, Single[] positions)
   at Tensorflow.Keras.Engine.Model.summary(Int32 line_length, Single[] positions)
   at TFLearnNET.NnTask.BuildModel() in C:\Users\shahe\Desktop\Development\AI\TFLearnNET\TFLearnNET\NnTask.cs:line 100
```

Model.train(): 
```
Unhandled exception. Tensorflow.InvalidArgumentError: Value for attr 'T' of uint8 is not in the list of allowed values: bfloat16, half, float, double, int32, int64, complex64, complex128; NodeDef: {{node dense/MatMul}}; Op<name=MatMul; signature=a:T, b:T -> product:T; attr=transpose_a:bool,default=false; attr=transpose_b:bool,default=false; attr=T:type,allowed=[DT_BFLOAT16, DT_HALF, DT_FLOAT, DT_DOUBLE, DT_INT32, DT_INT64, DT_COMPLEX64, DT_COMPLEX128]>
   at Tensorflow.ops._create_c_op(Graph graph, NodeDef node_def, Tensor[] inputs, Operation[] control_inputs, OpDef op_def)
   at Tensorflow.Operation..ctor(NodeDef node_def, Graph g, Tensor[] inputs, TF_DataType[] output_types, ITensorOrOperation[] control_inputs, TF_DataType[] input_types, String original_op, OpDef op_def)
   at Tensorflow.Graph.create_op(String op_type, Tensor[] inputs, TF_DataType[] dtypes, TF_DataType[] input_types, String name, Dictionary`2 attrs, OpDef op_def, Boolean compute_device)
   at Tensorflow.Graphs.FuncGraph.create_op(String op_type, Tensor[] inputs, TF_DataType[] dtypes, TF_DataType[] input_types, String name, Dictionary`2 attrs, OpDef op_def, Boolean compute_device)
   at Tensorflow.OpDefLibrary._apply_op_helper(String op_type_name, String name, Dictionary`2 keywords)
   at Tensorflow.Contexts.Context.ExecGraphAction(String OpType, String Name, ExecuteOpArgs args)
   at Tensorflow.Contexts.Context.ExecuteOp(String opType, String name, ExecuteOpArgs args)
   at Tensorflow.gen_math_ops.mat_mul(Tensor a, Tensor b, Boolean transpose_a, Boolean transpose_b, String name)
   at Tensorflow.Keras.Layers.Dense.Call(Tensors inputs, Tensor state, Nullable`1 training)
   at Tensorflow.Keras.Engine.Layer.FunctionalConstructionCall(Tensors inputs)
   at Tensorflow.Keras.Engine.Layer.Apply(Tensors inputs, Tensor state, Boolean training)
   at Tensorflow.Keras.Engine.Sequential._build_graph_network_for_inferred_shape(Shape input_shape, TF_DataType input_dtype)
   at Tensorflow.Keras.Engine.Sequential.Call(Tensors inputs, Tensor state, Nullable`1 training)
   at Tensorflow.Keras.Engine.Layer.Apply(Tensors inputs, Tensor state, Boolean training)
   at Tensorflow.Keras.Engine.Model.train_step(Tensor x, Tensor y)
   at Tensorflow.Keras.Engine.Model.train_step_function(OwnedIterator iterator)
   at Tensorflow.Keras.Engine.Model.FitInternal(Int32 epochs, Int32 verbose)
   at Tensorflow.Keras.Engine.Model.fit(NDArray x, NDArray y, Int32 batch_size, Int32 epochs, Int32 verbose, Single validation_split, Boolean shuffle, Int32 initial_epoch, Int32 max_queue_size, Int32 workers, Boolean use_multiprocessing)
   at TFLearnNET.NnTask.TrainModel() in C:\Users\shahe\Desktop\Development\AI\TFLearnNET\TFLearnNET\NnTask.cs:line 105
```

**Comment by j-baudot** [comment]
Hey hi !

Same error raising on my side (except I do not compile() my model before trying to get a summary() ).

Any update ? Any experiment to share ?

Thanks,
J

**Comment by TheBlackPlague** [comment]
> Hey hi !
> 
> Same error raising on my side (except I do not compile() my model before trying to get a summary() ).
> 
> Any update ? Any experiment to share ?
> 
> Thanks, J

Hello,

Sorry for my late response. Have been quite busy lately.

Sadly not. I gave up on this library a while ago.
