### ISSUE TITLE
load_weight throws exception: Tensorflow.InvalidArgumentError: 'Value for attr 'T' of uint8 is not in the list of allowed values

### ISSUE THREAD

**Issue by ismasanchez** [SciSharp/TensorFlow.NET#955]
With the following code a model is correctly saved:

Model model;
NDArray x_train, y_train, x_test, y_test;

(x_train, y_train, x_test, y_test) = keras.datasets.mnist.load_data();
x_train = x_train.reshape((60000, 784)) / 255f;
x_test = x_test.reshape((10000, 784)) / 255f;

var inputs = keras.Input(shape: 784);

// 1st dense layer
var outputs = keras.layers.Dense(64, activation: keras.activations.Relu).Apply(inputs);

// 2nd dense layer
outputs = keras.layers.Dense(64, activation: keras.activations.Relu).Apply(outputs);

// output layer
outputs = keras.layers.Dense(10).Apply(outputs);

// build keras model
model = keras.Model(inputs, outputs, name: "mnist_model");
// show model summary

model.compile(loss: keras.losses.SparseCategoricalCrossentropy(from_logits: true),
    optimizer: keras.optimizers.RMSprop(),
    metrics: new[] { "accuracy" });

model.fit(x_train, y_train, batch_size: 64, epochs: 2, validation_split: 0.2f);

// evluate the model
model.evaluate(x_test, y_test, verbose: 2);

// save and serialize model
model.save_weights("mnist_weights");

But with the following code it throws exception when loading weights:

var inputs = keras.Input(shape: 784);

// 1st dense layer
var outputs = keras.layers.Dense(64, activation: keras.activations.Relu).Apply(inputs);

// 2nd dense layer
outputs = keras.layers.Dense(64, activation: keras.activations.Relu).Apply(outputs);

// output layer
outputs = keras.layers.Dense(10).Apply(outputs);

// build keras model
model = keras.Model(inputs, outputs, name: "mnist_model");
// show model summary

// load keras model
model.load_weights("mnist_weights");

(x_train, y_train, x_test, y_test) = keras.datasets.mnist.load_data();

model.evaluate(x_test, y_test, verbose: 2);

Tensorflow.InvalidArgumentError
  HResult=0x80131500
  Message=Value for attr 'T' of uint8 is not in the list of allowed values: bfloat16, half, float, double, int32, int64, complex64, complex128
	; NodeDef: {{node MatMul}}; Op<name=MatMul; signature=a:T, b:T -> product:T; attr=transpose_a:bool,default=false; attr=transpose_b:bool,default=false; attr=T:type,allowed=[DT_BFLOAT16, DT_HALF, DT_FLOAT, DT_DOUBLE, DT_INT32, DT_INT64, DT_COMPLEX64, DT_COMPLEX128]>
  Source=Tensorflow.Binding
  StackTrace:
   at Tensorflow.Eager.EagerRunner.TFE_FastPathExecute(FastPathOpExecInfo op_exec_info)
   at Tensorflow.Contexts.Context.ExecEagerAction(String OpType, String Name, ExecuteOpArgs args)
   at Tensorflow.Contexts.Context.ExecuteOp(String opType, String name, ExecuteOpArgs args)
   at Tensorflow.gen_math_ops.mat_mul(Tensor a, Tensor b, Boolean transpose_a, Boolean transpose_b, String name)
   at Tensorflow.math_ops.<>c__DisplayClass65_0.<matmul>b__0(NameScope scope)
   at Tensorflow.math_ops.matmul(Tensor a, Tensor b, Boolean transpose_a, Boolean transpose_b, Boolean adjoint_a, Boolean adjoint_b, Boolean a_is_sparse, Boolean b_is_sparse, String name)
   at Tensorflow.math_ops.<>c__DisplayClass70_0.<tensordot>b__0(NameScope scope)
   at Tensorflow.math_ops.tensordot(Tensor a, Tensor b, NDArray axes, String name)
   at Tensorflow.Keras.Layers.Dense.Call(Tensors inputs, Tensor state, Nullable`1 training)
   at Tensorflow.Keras.Engine.Layer.Apply(Tensors inputs, Tensor state, Boolean training)
   at Tensorflow.Keras.Engine.Functional.Call(Tensors inputs, Tensor state, Nullable`1 training)
   at Tensorflow.Keras.Engine.Layer.Apply(Tensors inputs, Tensor state, Boolean training)
   at Tensorflow.Keras.Engine.Model.test_step(Tensor x, Tensor y)
   at Tensorflow.Keras.Engine.Model.test_function(OwnedIterator iterator)
   at Tensorflow.Keras.Engine.Model.evaluate(NDArray x, NDArray y, Int32 batch_size, Int32 verbose, Int32 steps, Int32 max_queue_size, Int32 workers, Boolean use_multiprocessing, Boolean return_dict)
   at Program.<Main>$(String[] args) in D:\Projects\AI\Tests\TensorFlowTest\MinstExampleKeras\Program.cs:line 73

**Comment by ismasanchez** [comment]
My fault, the x_test values should have been divided by float 255 like this:

(x_train, y_train, x_test, y_test) = keras.datasets.mnist.load_data();
x_test = x_test.reshape((10000, 784)) / 255f;

model.evaluate(x_test, y_test, verbose: 2);

But now I get NullReference exception on function model.evaluate:

System.NullReferenceException
  HResult=0x80004003
  Message=Object reference not set to an instance of an object.
  Source=Tensorflow.Keras
  StackTrace:
   at Tensorflow.Keras.Engine.Model.test_step(Tensor x, Tensor y)
   at Tensorflow.Keras.Engine.Model.test_function(OwnedIterator iterator)
   at Tensorflow.Keras.Engine.Model.evaluate(NDArray x, NDArray y, Int32 batch_size, Int32 verbose, Int32 steps, Int32 max_queue_size, Int32 workers, Boolean use_multiprocessing, Boolean return_dict)
   at Program.<Main>$(String[] args) in D:\Projects\AI\Tests\TensorFlowTest\MinstExampleKeras\Program.cs:line 74

Looks like weights aren't loaded in the model:

![image](https://user-images.githubusercontent.com/41548471/201667610-410c056c-0664-4320-b824-ad90ea45e629.png)

**Comment by Oceania2018** [comment]
@ismasanchez I run it locally, it works no any problem. I paste the sample code here:
```csharp
public void Predict()
{
    var inputs = keras.Input(shape: 784);

    // 1st dense layer
    var outputs = keras.layers.Dense(64, activation: keras.activations.Relu).Apply(inputs);

    // 2nd dense layer
    outputs = keras.layers.Dense(64, activation: keras.activations.Relu).Apply(outputs);

    // output layer
    outputs = keras.layers.Dense(10).Apply(outputs);

    // build keras model
    model = keras.Model(inputs, outputs, name: "mnist_model");

    // compile model
    model.compile(loss: keras.losses.SparseCategoricalCrossentropy(from_logits: true),
        optimizer: keras.optimizers.RMSprop(),
        metrics: new[] { "accuracy" });

    // show model summary

    // load keras model
    model.load_weights("mnist_weights");

    (x_train, y_train, x_test, y_test) = keras.datasets.mnist.load_data();

    x_train = x_train.reshape((60000, 784)) / 255f;
    x_test = x_test.reshape((10000, 784)) / 255f;

    model.evaluate(x_test, y_test, verbose: 2);
}
```
```console
Microsoft Windows NT 10.0.22621.0
64Bit Operating System: True
.NET CLR: 6.0.11
TensorFlow Binary v2.10.0
TensorFlow.NET v0.100.0.0
TensorFlow.Keras v0.10.0.0
C:\Users\haipi\source\repos\SciSharp\SciSharp-Stack-Examples\src\TensorFlowNET.Examples\bin\Debug\net6.0
2022-11-14 07:03:49.533123: I tensorflow/core/platform/cpu_feature_guard.cc:193] This TensorFlow binary is optimized with oneAPI Deep Neural Network Library (oneDNN) to use the following CPU instructions in performance-critical operations:  AVX2
To enable them in other operations, rebuild TensorFlow with the appropriate compiler flags.
The file C:\Users\haipi\AppData\Local\Temp\mnist.npz already exists
Testing...
iterator: 1, loss: 0.12638746, accuracy: 0.9628
```

**Comment by ismasanchez** [comment]
@Oceania2018 correct, now it works, I missed the following:

  model.compile(loss: keras.losses.SparseCategoricalCrossentropy(from_logits: true),
        optimizer: keras.optimizers.RMSprop(),
        metrics: new[] { "accuracy" });

You can close this issue, thanks for your quick response.
