### ISSUE TITLE
Multithreading with Keras and `model.make_predict_function()`

### ISSUE THREAD

**Issue by matthew-e-brown** [SciSharp/TensorFlow.NET#958]
I've written a small ASP.NET server to accept data as input into a Keras model. Everything was working fine in testing, until it came time to actually send a POST request. When running `Model.predict` in an `async` call, I get the following error:

```none
fail: Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddleware[1]
      An unhandled exception has occurred while executing the request.
      Tensorflow.RuntimeError: Attempting to capture an EagerTensor without building a function.
         at Tensorflow.ops.convert_to_tensor(Object value, TF_DataType dtype, String name, Boolean as_ref, TF_DataType preferred_dtype, Context ctx)
         at Tensorflow.OpDefLibrary._apply_op_helper(String op_type_name, String name, Dictionary`2 keywords)
         at Tensorflow.Contexts.Context.ExecGraphAction(String OpType, String Name, ExecuteOpArgs args)
         at Tensorflow.Contexts.Context.ExecuteOp(String opType, String name, ExecuteOpArgs args)
         at Tensorflow.gen_resource_variable_ops.read_variable_op(Tensor resource, TF_DataType dtype, String name)
         at Tensorflow.BaseResourceVariable._read_variable_op()
         at Tensorflow.BaseResourceVariable.read_value()
         at Tensorflow.BaseResourceVariable.numpy()
         at Tensorflow.Keras.Engine.DataAdapters.DataHandler..ctor(DataHandlerArgs args)
         at Tensorflow.Keras.Engine.Model.predict(Tensor x, Int32 batch_size, Int32 verbose, Int32 steps, Int32 max_queue_size, Int32 workers, Boolean use_multiprocessing)
         at NeuralNetwork.Predict(Byte[] data) in C:\Users\Matthew\...\Project\NeuralNetwork\NeuralNetwork.cs:line 129
         at Program.<>c__DisplayClass0_0.<<<Main>$>b__0>d.MoveNext() in C:\Users\Matthew\...\Project\Server\Program.cs:line 29
      --- End of stack trace from previous location ---
         at Microsoft.AspNetCore.Http.RequestDelegateFactory.ExecuteTaskResult[T](Task`1 task, HttpContext httpContext)
         at Microsoft.AspNetCore.Routing.EndpointMiddleware.<Invoke>g__AwaitRequestTask|6_0(Endpoint endpoint, Task requestTask, ILogger logger)
         at Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddleware.Invoke(HttpContext context)
```

Everything I've seen online regarding this "Attempting to capture EagerTensor" error has said that it's due to multithreading, and [the advice I see][gh] in several places involves saving the graph and session to `with` or `using` them later, as well as pre-compiling the prediction function. They all say to use this function called `model.make_predict_function()` or `model._make_predict_function()` -- that sounds like exactly what I need: it'll pre-compile the prediction function for use in other threads.

Except... I cannot find that function ***anywhere*** in Tensorflow.NET's bindings. I have spent a hours digging through documentation and Intellisense popups trying to find this function somewhere, but I can't. What is Tensorflow.NET's recommendation for dealing with Keras in `async` calls or other threads? Is there some other approach to use?

Thanks.

---

P.S., I can provide the code for the network if required. It's for a school project, so it's basically as barebones-`Hello World` as it gets.

[gh]: https://github.com/keras-team/keras/issues/2397#issuecomment-306687500

**Comment by matthew-e-brown** [comment]
I've just gone and refactored my function and found that it doesn't work even when using a non-`async` function.

I've put the code for this example up on a GitHub Gist: https://gist.github.com/matthew-e-brown/5dfeb557b4f2b0de90c8659760dd5131

**Comment by Oceania2018** [comment]
@matthew-e-brown I added your example into the [Example](https://github.com/SciSharp/SciSharp-Stack-Examples) project.
![image](https://user-images.githubusercontent.com/1705364/205463315-a20594a4-c7f3-40a8-b2ff-74bd24d22aa7.png)
It should work as below:
![image](https://user-images.githubusercontent.com/1705364/205463352-443b1283-15b0-466e-a2e6-54000d28b8bf.png)
